server:
  port: 8080


  
  jackson:
    date-format: yyyy-MM-dd
    time-zone: GMT+8
      
mybatis:
  mapper-locations:
  - classpath*:/mappers/**/*.xml
  type-aliases-package: com.neusoft.wuyemis.baseinfo.model,com.neusoft.wuyemis.admin.model,com.neusoft.wuyemis.feeinfo.model
 
logging:
  level:
    com.neusoft.wuyemis.mapper: debug
    


